### ISSUE TITLE
Instructions not clear.

### ISSUE THREAD

**Issue by ziplock9000** [Zarbuz/VoxMerger#2]
The instructions only show the format for one input file, so had to guess how to pick two for the merge.

Tried:
voxmerger.exe --i house1 --i house2 --o house
voxmerger.exe --i house1.vox --i house2.vox --o house.vox

All vox files, exe and dlls are in same folder.

Error:
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\ziplo\OneDrive\Desktop\Football Supporter Simulator\VOX\Foreground\house2'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at VoxMerger.Program.ProcessFolder(String inputFolder, String outputFile, Boolean logs, Boolean debug) in D:\Downloads\VoxMerger-master\VoxMerger-master\Program.cs:line 40
   at VoxMerger.Program.Main(String[] args) in D:\Downloads\VoxMerger-master\VoxMerger-master\Program.cs:line 31

**Comment by Zarbuz** [comment]
"house1" must be a folder where there is all your .vox files. "house2" will be a .vox file

**Comment by ziplock9000** [comment]
I got this working thanks.
