### ISSUE TITLE
Encountering Sequence contains no elements

### ISSUE THREAD

**Issue by sand3sh** [Zarbuz/VoxMerger#6]
I was able to merge other Vox files but few specific files I am encountering error 'Sequence contains no elements' . Both are basic  single vox model file one 40x40 other 128x128 however getting below error. Can you tell me what might be the issue.

[LOG] Started to load model: C:\opt\MagicaVoxel-0.99.6.4-win64\testmerger\input\cigar.vox
[LOG] Started to load model: C:\opt\MagicaVoxel-0.99.6.4-win64\testmerger\input\crown.vox
[INFO] Total blocks: 2337
[LOG] Started to create an optimized palette...
[LOG] Done.
[LOG] Chunk RGBA: 1036
[LOG] Chunk MATL: 16302
[LOG] Chunk SIZE: 72
[LOG] Chunk XYZI: 9396
[LOG] Chunk nGRP: 28
[LOG] Chunk nTRN: 133
[LOG] Chunk nSHP: 32
[LOG] Chunk MnTRN: 40
[LOG] Chunk MnGRP: 36
[LOG] Step [1/2]: Started to write SIZE and XYZI...
[LOG] Done.

Unhandled Exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at VoxMerger.Vox.VoxWriterCustom.WriteChunks(BinaryWriter writer) in E:\Documents\VoxMerger\Vox\VoxWriterCustom.cs:line 189
   at VoxMerger.Vox.VoxWriterCustom.WriteModel(String absolutePath, List`1 models) in E:\Documents\VoxMerger\Vox\VoxWriterCustom.cs:line 32
   at VoxMerger.Program.ProcessFolder(String inputFolder, String outputFile, Boolean logs, Boolean debug) in E:\Documents\VoxMerger\Program.cs:line 64
   at VoxMerger.Program.Main(String[] args) in E:\Documents\VoxMerger\Program.cs:line 31

**Comment by Zarbuz** [comment]
Can you provide the vox which provide the bug please?
